// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "890bb416-ee6d-4641-b9ab-ddafcd68c061";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSecurityActivationChange();

CloudColoredLight rgb_LED;
int sound_value;
bool currentState;
bool securityActivation;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(rgb_LED, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(sound_value, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(currentState, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(securityActivation, READWRITE, ON_CHANGE, onSecurityActivationChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
